# Generated by Django 3.0.2 on 2025-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(starting_bid__gt=0), name='starting_bid_gt_0'),
        ),
    ]
