# Generated by Django 3.0.2 on 2025-12-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics')], max_length=50, null=True),
        ),
    ]
